import mlx.core as mx

from mflux.models.common.lora.mapping.lora_mapping import LoRAMapping, LoRATarget


class ZImageLoRAMapping(LoRAMapping):
    @staticmethod
    def get_mapping() -> list[LoRATarget]:
        targets = []
        for layer_type in ["layers", "noise_refiner", "context_refiner"]:
            targets.extend(ZImageLoRAMapping._get_layer_targets(layer_type))
        targets.extend(ZImageLoRAMapping._get_global_targets())
        targets.extend(ZImageLoRAMapping._get_comfy_targets())
        return targets

    @staticmethod
    def _split_qkv(weight: mx.array, index: int) -> mx.array:
        # Z-Image's fused projection stacks whole q, k and v blocks along the output axis.
        if weight.ndim != 2 or weight.shape[0] % 3:
            raise ValueError(f"Fused attention.qkv LoRA up weight {weight.shape} does not split into three equal parts")
        return mx.split(weight, 3, axis=0)[index]

    @staticmethod
    def _get_comfy_targets() -> list[LoRATarget]:
        targets = []
        for layer_type in ("layers", "noise_refiner", "context_refiner"):
            block = f"{layer_type}.{{block}}"
            source = f"diffusion_model.{block}"
            for index, projection in enumerate(("to_q", "to_k", "to_v")):
                targets.append(
                    LoRATarget(
                        model_path=f"{block}.attention.{projection}",
                        possible_up_patterns=[f"{source}.attention.qkv.lora_up.weight"],
                        possible_down_patterns=[f"{source}.attention.qkv.lora_down.weight"],
                        possible_alpha_patterns=[f"{source}.attention.qkv.alpha"],
                        up_transform=lambda weight, index=index: ZImageLoRAMapping._split_qkv(weight, index),
                    )
                )
            for source_norm, target_norm in (
                ("attention.q_norm", "attention.norm_q"),
                ("attention.k_norm", "attention.norm_k"),
                ("attention_norm1", "attention_norm1"),
                ("attention_norm2", "attention_norm2"),
                ("ffn_norm1", "ffn_norm1"),
                ("ffn_norm2", "ffn_norm2"),
            ):
                targets.append(
                    LoRATarget(
                        model_path=f"{block}.{target_norm}",
                        possible_up_patterns=[],
                        possible_down_patterns=[],
                        possible_diff_patterns=[f"{source}.{source_norm}.diff"],
                    )
                )
            if layer_type != "context_refiner":
                targets.append(
                    LoRATarget(
                        model_path=f"{block}.adaLN_modulation.0",
                        possible_up_patterns=[],
                        possible_down_patterns=[],
                        possible_diff_b_patterns=[f"{source}.adaLN_modulation.0.diff_b"],
                    )
                )

        for source, target in (
            ("x_embedder", "all_x_embedder.2-1"),
            ("final_layer.linear", "all_final_layer.2-1.linear"),
            ("final_layer.adaLN_modulation.1", "all_final_layer.2-1.adaLN_modulation.0"),
            ("cap_embedder.1", "cap_embedder.1"),
            ("t_embedder.mlp.0", "t_embedder.linear1"),
            ("t_embedder.mlp.2", "t_embedder.linear2"),
        ):
            targets.append(
                LoRATarget(
                    model_path=target,
                    possible_up_patterns=[f"diffusion_model.{source}.lora_up.weight"],
                    possible_down_patterns=[f"diffusion_model.{source}.lora_down.weight"],
                    possible_alpha_patterns=[f"diffusion_model.{source}.alpha"],
                    possible_diff_b_patterns=[f"diffusion_model.{source}.diff_b"],
                )
            )
        targets.append(
            LoRATarget(
                model_path="cap_embedder.0",
                possible_up_patterns=[],
                possible_down_patterns=[],
                possible_diff_patterns=["diffusion_model.cap_embedder.0.diff"],
            )
        )
        return targets

    @staticmethod
    def _get_global_targets() -> list[LoRATarget]:
        return [
            LoRATarget(
                model_path="all_x_embedder.2-1",
                possible_up_patterns=[
                    "diffusion_model.all_x_embedder.2-1.lora_B.weight",
                    "diffusion_model.all_x_embedder.2-1.lora_B.default.weight",
                    "transformer.all_x_embedder.2-1.lora_B.weight",
                    "transformer.all_x_embedder.2-1.lora_B.default.weight",
                ],
                possible_down_patterns=[
                    "diffusion_model.all_x_embedder.2-1.lora_A.weight",
                    "diffusion_model.all_x_embedder.2-1.lora_A.default.weight",
                    "transformer.all_x_embedder.2-1.lora_A.weight",
                    "transformer.all_x_embedder.2-1.lora_A.default.weight",
                ],
            ),
            LoRATarget(
                model_path="all_final_layer.2-1.linear",
                possible_up_patterns=[
                    "diffusion_model.all_final_layer.2-1.linear.lora_B.weight",
                    "diffusion_model.all_final_layer.2-1.linear.lora_B.default.weight",
                    "transformer.all_final_layer.2-1.linear.lora_B.weight",
                    "transformer.all_final_layer.2-1.linear.lora_B.default.weight",
                ],
                possible_down_patterns=[
                    "diffusion_model.all_final_layer.2-1.linear.lora_A.weight",
                    "diffusion_model.all_final_layer.2-1.linear.lora_A.default.weight",
                    "transformer.all_final_layer.2-1.linear.lora_A.weight",
                    "transformer.all_final_layer.2-1.linear.lora_A.default.weight",
                ],
            ),
            LoRATarget(
                model_path="all_final_layer.2-1.adaLN_modulation.0",
                possible_up_patterns=[
                    "diffusion_model.all_final_layer.2-1.adaLN_modulation.1.lora_B.weight",
                    "diffusion_model.all_final_layer.2-1.adaLN_modulation.1.lora_B.default.weight",
                    "transformer.all_final_layer.2-1.adaLN_modulation.1.lora_B.weight",
                    "transformer.all_final_layer.2-1.adaLN_modulation.1.lora_B.default.weight",
                ],
                possible_down_patterns=[
                    "diffusion_model.all_final_layer.2-1.adaLN_modulation.1.lora_A.weight",
                    "diffusion_model.all_final_layer.2-1.adaLN_modulation.1.lora_A.default.weight",
                    "transformer.all_final_layer.2-1.adaLN_modulation.1.lora_A.weight",
                    "transformer.all_final_layer.2-1.adaLN_modulation.1.lora_A.default.weight",
                ],
            ),
            LoRATarget(
                model_path="cap_embedder.1",
                possible_up_patterns=[
                    "diffusion_model.cap_embedder.1.lora_B.weight",
                    "diffusion_model.cap_embedder.1.lora_B.default.weight",
                    "transformer.cap_embedder.1.lora_B.weight",
                    "transformer.cap_embedder.1.lora_B.default.weight",
                ],
                possible_down_patterns=[
                    "diffusion_model.cap_embedder.1.lora_A.weight",
                    "diffusion_model.cap_embedder.1.lora_A.default.weight",
                    "transformer.cap_embedder.1.lora_A.weight",
                    "transformer.cap_embedder.1.lora_A.default.weight",
                ],
            ),
            LoRATarget(
                model_path="t_embedder.linear1",
                possible_up_patterns=[
                    "diffusion_model.t_embedder.mlp.0.lora_B.weight",
                    "diffusion_model.t_embedder.mlp.0.lora_B.default.weight",
                    "transformer.t_embedder.mlp.0.lora_B.weight",
                    "transformer.t_embedder.mlp.0.lora_B.default.weight",
                ],
                possible_down_patterns=[
                    "diffusion_model.t_embedder.mlp.0.lora_A.weight",
                    "diffusion_model.t_embedder.mlp.0.lora_A.default.weight",
                    "transformer.t_embedder.mlp.0.lora_A.weight",
                    "transformer.t_embedder.mlp.0.lora_A.default.weight",
                ],
            ),
            LoRATarget(
                model_path="t_embedder.linear2",
                possible_up_patterns=[
                    "diffusion_model.t_embedder.mlp.2.lora_B.weight",
                    "diffusion_model.t_embedder.mlp.2.lora_B.default.weight",
                    "transformer.t_embedder.mlp.2.lora_B.weight",
                    "transformer.t_embedder.mlp.2.lora_B.default.weight",
                ],
                possible_down_patterns=[
                    "diffusion_model.t_embedder.mlp.2.lora_A.weight",
                    "diffusion_model.t_embedder.mlp.2.lora_A.default.weight",
                    "transformer.t_embedder.mlp.2.lora_A.weight",
                    "transformer.t_embedder.mlp.2.lora_A.default.weight",
                ],
            ),
        ]

    @staticmethod
    def _get_layer_targets(layer_type: str) -> list[LoRATarget]:
        return [
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.adaLN_modulation.0",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_up.default.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_B.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_B.default.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_up.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_adaLN_modulation_0.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_adaLN_modulation_0.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.lora_down.default.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_A.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_A.default.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_down.weight",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_adaLN_modulation_0.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_adaLN_modulation_0.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.adaLN_modulation.0.alpha",
                    f"transformer.{layer_type}.{{block}}.adaLN_modulation.0.alpha",
                    f"{layer_type}.{{block}}.adaLN_modulation.0.alpha",
                    f"lora_unet_{layer_type}_{{block}}_adaLN_modulation_0.alpha",
                ],
            ),
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.attention.to_q",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_up.default.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_B.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_B.default.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_up.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_q.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_q.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.lora_down.default.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_A.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_A.default.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_down.weight",
                    f"{layer_type}.{{block}}.attention.to_q.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_q.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_q.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_q.alpha",
                    f"transformer.{layer_type}.{{block}}.attention.to_q.alpha",
                    f"{layer_type}.{{block}}.attention.to_q.alpha",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_q.alpha",
                ],
            ),
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.attention.to_k",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_up.default.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_B.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_B.default.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_up.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_k.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_k.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.lora_down.default.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_A.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_A.default.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_down.weight",
                    f"{layer_type}.{{block}}.attention.to_k.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_k.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_k.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_k.alpha",
                    f"transformer.{layer_type}.{{block}}.attention.to_k.alpha",
                    f"{layer_type}.{{block}}.attention.to_k.alpha",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_k.alpha",
                ],
            ),
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.attention.to_v",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_up.default.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_B.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_B.default.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_up.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_v.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_v.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.lora_down.default.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_A.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_A.default.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_down.weight",
                    f"{layer_type}.{{block}}.attention.to_v.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_v.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_v.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_v.alpha",
                    f"transformer.{layer_type}.{{block}}.attention.to_v.alpha",
                    f"{layer_type}.{{block}}.attention.to_v.alpha",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_v.alpha",
                ],
            ),
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.attention.to_out.0",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_up.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_up.default.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_B.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_B.default.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_up.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_out_0.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_out_0.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.lora_down.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.attention.out.lora_down.default.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_A.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_A.default.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_down.weight",
                    f"{layer_type}.{{block}}.attention.to_out.0.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_out_0.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_out_0.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.attention.to_out.0.alpha",
                    f"diffusion_model.{layer_type}.{{block}}.attention.out.alpha",
                    f"transformer.{layer_type}.{{block}}.attention.to_out.0.alpha",
                    f"transformer.{layer_type}.{{block}}.attention.out.alpha",
                    f"{layer_type}.{{block}}.attention.to_out.0.alpha",
                    f"lora_unet_{layer_type}_{{block}}_attention_to_out_0.alpha",
                ],
            ),
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.feed_forward.w1",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_up.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_B.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_B.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_up.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w1.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w1.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.lora_down.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_A.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_A.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_down.weight",
                    f"{layer_type}.{{block}}.feed_forward.w1.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w1.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w1.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w1.alpha",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w1.alpha",
                    f"{layer_type}.{{block}}.feed_forward.w1.alpha",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w1.alpha",
                ],
            ),
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.feed_forward.w2",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_up.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_B.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_B.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_up.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w2.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w2.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.lora_down.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_A.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_A.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_down.weight",
                    f"{layer_type}.{{block}}.feed_forward.w2.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w2.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w2.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w2.alpha",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w2.alpha",
                    f"{layer_type}.{{block}}.feed_forward.w2.alpha",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w2.alpha",
                ],
            ),
            LoRATarget(
                model_path=f"{layer_type}.{{block}}.feed_forward.w3",
                possible_up_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_B.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_B.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_up.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_up.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_B.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_B.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_up.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_up.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_B.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_B.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_up.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_up.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w3.lora_up.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w3.lora_up.default.weight",
                ],
                possible_down_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_A.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_A.default.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_down.weight",
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.lora_down.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_A.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_A.default.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_down.weight",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.lora_down.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_A.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_A.default.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_down.weight",
                    f"{layer_type}.{{block}}.feed_forward.w3.lora_down.default.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w3.lora_down.weight",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w3.lora_down.default.weight",
                ],
                possible_alpha_patterns=[
                    f"diffusion_model.{layer_type}.{{block}}.feed_forward.w3.alpha",
                    f"transformer.{layer_type}.{{block}}.feed_forward.w3.alpha",
                    f"{layer_type}.{{block}}.feed_forward.w3.alpha",
                    f"lora_unet_{layer_type}_{{block}}_feed_forward_w3.alpha",
                ],
            ),
        ]
